package nl.maartenbodewes.rng_bc;

import java.security.SecureRandom;

/**
 * Local class used to counts the random bits generated by the parent <code>SecureRandom</code>.
 * Note that this class does not override *all* methods that may return random numbers,
 * and may therefore not be accurate if those other methods are called. 
 *
 * @author maartenb
 */
final class CountingSecureRandom extends SecureRandom {

	private static final long serialVersionUID = 1L;
	
	private final SecureRandom parent;
	private long bitCount = 0L;
	
	public CountingSecureRandom(SecureRandom parent) {
		this.parent = parent;
	}
	
	@Override
	public void nextBytes(byte[] bytes) {
		bitCount += bytes.length * Byte.SIZE;
		parent.nextBytes(bytes);
	}
	
	@Override
	public int nextInt() {
		bitCount += Integer.SIZE;
		return parent.nextInt();
	}
	
	public long getBitCount() {
		return bitCount;
	}
	
	public void resetBitCount() {
		this.bitCount = 0L;
	}
}